@baseUrl = https://jz20g80jvl.execute-api.us-east-1.amazonaws.com/dev

### Check if the user is online at a given timestamp - timestamp not provided
GET {{baseUrl}}/schedule/1/check

### Check if the user is online at a given timestamp - no schedule found for the given userId
GET {{baseUrl}}/schedule/100/check?timestamp=1720171800

### Check if the user (2) is online at a given timestamp
### User Timezone: Asia/Calcutta 
### User Friday schedule from 16:00 to 20:00
### Provided Timestamp:(1719981000) Wednesday, July 3, 2024 10:00:00 AM GMT+05:30
### Result: Should be online
GET {{baseUrl}}/schedule/2/check?timestamp=1719981000

### get schedule by userId
GET {{baseUrl}}/schedule/2


### Check if the user (2) is offline at a given timestamp
### User Timezone: Asia/Kolkata 
### User Friday schedule from 16:00 to 20:00
### Provided Timestamp:(1720171800) Friday, July 5, 2024 3:00:00 PM GMT+05:30
### Result: Should be offline
GET {{baseUrl}}/schedule/2/check?timestamp=1720171800

