@createScheduleBaseUrl = https://vfkbwzj1dc.execute-api.us-east-1.amazonaws.com/dev

###########################################################################
### Check if the user is online at a given timestamp - timestamp not provided
GET {{createScheduleBaseUrl}}/schedule/1/check

###########################################################################
### Check if the user is online at a given timestamp - no schedule found for the given userId
GET {{createScheduleBaseUrl}}/schedule/100/check?timestamp=1720171800

###########################################################################
### Check if the user (2) is online at a given timestamp
### User Timezone: Asia/Calcutta 
### User Wednesday schedule from 09:00 to 12:00
### Provided Timestamp:(1719981000) Wednesday, July 3, 2024 10:00:00 AM GMT+05:30 (10:00)
### Result: Should be online
GET {{createScheduleBaseUrl}}/schedule/2/check?timestamp=1719981000

###########################################################################
### get schedule by userId
GET {{createScheduleBaseUrl}}/schedule/3

###########################################################################
### Check if the user (2) is offline at a given timestamp
### User Timezone: Asia/Kolkata 
### User Friday schedule from 09:00 to 12:00
### Provided Timestamp:(1719948600) Wednesday, July 3, 2024 1:00:00 AM GMT+05:30 
### Result: Should be offline
GET {{createScheduleBaseUrl}}/schedule/2/check?timestamp=1719948600


###########################################################################
### Check if the user (4) is online at a given timestamp
### User Timezone: America/New_York 
### User Friday schedule from 09:00 to 17:00
### Provided Timestamp:(1720209600) Friday, July 5, 2024 04:00:00 PM UTC-04:00 
### Result: Should be online
GET {{createScheduleBaseUrl}}/schedule/3/check?timestamp=1720209600

###########################################################################
### Check if the user (4) is offline at a given timestamp
### User Timezone: America/New_York 
### User Friday schedule from 09:00 to 17:00
### Provided Timestamp:(1720216800) Friday, July 5, 2024 06:00:00 PM UTC-04:00
### Result: Should be online
GET {{createScheduleBaseUrl}}/schedule/3/check?timestamp=1720216800

