@createScheduleBaseUrl = https://vfkbwzj1dc.execute-api.us-east-1.amazonaws.com/dev

### create user schedule (Valid Request)
POST {{createScheduleBaseUrl}}/schedule
Content-Type: application/json

{
  "schedule": {
    "Monday": [{ "start": "09:00", "end": "17:00" }],
    "Tuesday": [{ "start": "13:00", "end": "17:00" }],
    "Wednesday": [
      { "start": "09:00", "end": "12:00" },
      { "start": "13:00", "end": "17:00" }
    ],
    "Thursday": [{ "start": "09:00", "end": "17:00" }],
    "Friday": [{ "start": "09:00", "end": "17:00" }],
    "Saturday": [],
    "Sunday": []
  },
  "timezone": "America/New_York"
}

### create user schedule (Invalid Timezone)
POST {{createScheduleBaseUrl}}/schedule
Content-Type: application/json

{
  "schedule": {
    "Monday": [{ "start": "09:00", "end": "17:00" }],
    "Tuesday": [{ "start": "13:00", "end": "17:00" }],
    "Wednesday": [
      { "start": "09:00", "end": "12:00" },
      { "start": "13:00", "end": "17:00" }
    ],
    "Thursday": [{ "start": "09:00", "end": "17:00" }],
    "Friday": [{ "start": "09:00", "end": "17:00" }],
    "Saturday": [],
    "Sunday": []
  },
  "timezone": "Invalid_America/New_York"
}

### create user schedule (Invalid Time Period - Monday)
POST {{createScheduleBaseUrl}}/schedule
Content-Type: application/json

{
  "schedule": {
    "Monday": [{ "start": "INVALID:00", "end": "17:00" }],
    "Tuesday": [{ "start": "13:00", "end": "17:00" }],
    "Wednesday": [
      { "start": "09:00", "end": "12:00" },
      { "start": "13:00", "end": "17:00" }
    ],
    "Thursday": [{ "start": "09:00", "end": "17:00" }],
    "Friday": [{ "start": "09:00", "end": "17:00" }],
    "Saturday": [],
    "Sunday": []
  },
  "timezone": "America/New_York"
}

### create user schedule (Endtime not provided - Wednesday)
POST {{createScheduleBaseUrl}}/schedule
Content-Type: application/json

{
  "schedule": {
    "Monday": [{ "start": "09:00", "end": "17:00" }],
    "Tuesday": [{ "start": "13:00", "end": "17:00" }],
    "Wednesday": [
      { "start": "09:00" },
      { "start": "13:00", "end": "17:00" }
    ],
    "Thursday": [{ "start": "09:00", "end": "17:00" }],
    "Friday": [{ "start": "09:00", "end": "17:00" }],
    "Saturday": [],
    "Sunday": []
  },
  "timezone": "America/New_York"
}

### create user schedule 
### (overlapping times of the day - end is after the next start - Wednesday)
POST {{createScheduleBaseUrl}}/schedule
Content-Type: application/json

{
  "schedule": {
    "Monday": [{ "start": "09:00", "end": "17:00" }],
    "Tuesday": [{ "start": "13:00", "end": "17:00" }],
    "Wednesday": [
      { "start": "09:00", "end": "15:00" },
      { "start": "13:00", "end": "17:00" }
    ],
    "Thursday": [{ "start": "09:00", "end": "17:00" }],
    "Friday": [{ "start": "09:00", "end": "17:00" }],
    "Saturday": [],
    "Sunday": []
  },
  "timezone": "America/New_York"
}
