@createScheduleBaseUrl = https://vfkbwzj1dc.execute-api.us-east-1.amazonaws.com/dev

### get schedule by userId
GET {{createScheduleBaseUrl}}/schedule/1

###################################################################
### get schedule by userId - no records found
GET {{createScheduleBaseUrl}}/schedule/100
